# Generated by Django 3.2.3 on 2021-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tip',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tip',
            name='public_set',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
