# Generated by Django 3.2.3 on 2021-05-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210518_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='code',
        ),
        migrations.AlterField(
            model_name='tip',
            name='public_set',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='app.tip')),
            ],
            options={
                'db_table': 'code',
            },
        ),
    ]
