# Generated by Django 3.2.3 on 2021-05-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210520_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='filename',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
