# Generated by Django 3.2.3 on 2021-06-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notification_and_tip_uploadfile_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('is_read', '-created_at')},
        ),
    ]
