# Generated by Django 3.2.3 on 2021-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notification_ordering_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='filename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
