# Generated by Django 3.2.3 on 2021-06-12 13:58

import app.models
import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_createdat_to_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='uploadfile',
            field=models.FileField(blank=True, null=True, upload_to=app.models._tip_uploadfile_upload_to, validators=[app.validators.FileSizeValidator(byte_type='mb', val=3)]),
        ),
    ]
