# Generated by Django 3.2.3 on 2021-06-14 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_tip_uploadfile_add_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_users',
            field=models.ManyToManyField(blank=True, related_name='comment_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
