# Generated by Django 3.2.3 on 2021-06-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment_add_tousers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
