# Generated by Django 3.2.3 on 2021-07-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_notification_set_dbtable_str_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ('tip',)},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('tip',)},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('to_user', 'is_read', '-created_at')},
        ),
    ]
