# Generated by Django 3.2.3 on 2021-07-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='uploadfile',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='url',
        ),
        migrations.AddField(
            model_name='tip',
            name='tweet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='code',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('comment', 'コメント'), ('event', 'イベント'), ('follow', 'フォロー')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
