# Generated by Django 3.2.3 on 2021-06-09 08:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models._user_profile_icon_upload_to),
        ),
    ]
